### ISSUE TITLE
Nginx buffering is causing timeout issues in the Cloud Run instance of rubin-obs-api project

### ISSUE THREAD

**Issue by ericdrosas87** [lsst-epo/craft-base-image#3]
**Describe the bug**
_The downstream bug caused by this is bug is [here](https://github.com/lsst-epo/rubin-obs-api/issues/6), but a separate issue is written up here for posterity._

Nginx is timing out in the rubin-obs-api project, causing a myriad of side effects including failed rubin-obs-api builds.

**To Reproduce**
1. Log in to the Cloud Run instance's web dashboard
2. On the left-side menu: GraphQL->GraphiQL
3. Enter the following query:
```gql
{
  entries(type: "pages", site: "default") {
    id
    title
    slug
    typeHandle
  }
}
```
4. Click the right-pointed chevron "Execute Query" button

**Expected behavior**
The query results or an empty result set are returned

**Actual behavior**
The query never returns, returns a message stating the "upstream request failed", returns a 504 Nginx timeout issue, odd datatype definitions as JSON.

**Screenshots**
https://files.slack.com/files-pri/T06D204F2-F02HEM07REV/graphql_error.png

**Additional context**
GCP Logging Explorer trace URI:

projects/skyviewer/traces/414def70324239349fd3ddc1b8367a1a

**Comment by jtrouth** [comment]
Fixed in https://github.com/lsst-epo/craft-base-image/commit/9c2b06be790a8eafa929a4d15ec2bf16a7cf9861 by disabling (FastCGI buffering)[http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_buffering]. Having the buffering enabled caused prematurely truncated responses when running on Cloud Run for larger response sizes.
